/* eslint-disable react/prop-types */
import { animated } from "@react-spring/three";

export default function ConfettiRounded({ position, nodes, materials }) {
  return (
    <>
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
      <animated.mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.aiStandardSurface4SG}
        position={position}
      />
    </>
  );
}
